// <auto-generated />
using System;
using FlowUp.Workshops.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowUp.Workshops.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("FlowUp.Workshops.Api.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("FlowUp.Workshops.Api.Models.Participacao", b =>
                {
                    b.Property<int>("WorkshopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkshopId", "ColaboradorId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Participacoes");
                });

            modelBuilder.Entity("FlowUp.Workshops.Api.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("FlowUp.Workshops.Api.Models.Participacao", b =>
                {
                    b.HasOne("FlowUp.Workshops.Api.Models.Colaborador", "Colaborador")
                        .WithMany("Participacoes")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowUp.Workshops.Api.Models.Workshop", "Workshop")
                        .WithMany("Participacoes")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("FlowUp.Workshops.Api.Models.Colaborador", b =>
                {
                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("FlowUp.Workshops.Api.Models.Workshop", b =>
                {
                    b.Navigation("Participacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
